# Generated by Django 4.2.2 on 2023-06-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='dates',
            field=models.DateTimeField(),
        ),
    ]
